backend/Presentation/Controllers/InvestimentoController.cs
using ApplicationServices.IApplicationServices;
using AutoMapper;
using Domain.Entities._2BTrust;
using Domain.Enuns;
using Newtonsoft.Json;
using Presentation.Helpers;
using Presentation.Models._2BTrustModel;
using RestSharp;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;


namespace Presentation.Controllers
{
    public class EntradaPool
    {
        public string mValorCotas { get; set; }
        public int Cotas { get; set; }
        public int idPessoa { get; set; }
        public int idPoolBens { get; set; }
        public DateTime? DtInclusaoAdm { get; set; }
    }
    public class InvestimentoController : BaseController
    {
        // GET: Investimento  
        public async Task<ActionResult> ValidaRetiradaPlataforma()
        {
            IEnumerable<ComprovanteRetiradaModel> model;


            IRestResponse response = await PostRestAsync<ComprovanteRetirada>("/Pessoa/GetListRetiradaPendentes");
            if (response.StatusCode == System.Net.HttpStatusCode.OK)
            {
                model = JsonConvert.DeserializeObject<IEnumerable<ComprovanteRetiradaModel>>(response.Content);

                retorno.statusRetorno = ErrorMessageHttp.GetErrorMessage(response.StatusCode);
                retorno.objetoRetorno = model;

                return View(retorno);

            }
            else
            {
                retorno.statusRetorno = ErrorMessageHttp.GetErrorMessage(response.StatusCode);
                retorno.objetoRetorno = null;

                return View(retorno);
            }

            retorno.statusRetorno = ErrorMessageHttp.GetErrorMessage(System.Net.HttpStatusCode.ExpectationFailed);


            return View(retorno);
        }


        [HttpPost]
        public async Task<ActionResult> ValidaRetiradaPlataforma(int idComprovante, int idStatus)
        {
            //capturar comprovante by id
            var dto = new ComprovanteRetirada();
            IRestResponse response = await PostRestAsync<ComprovanteRetirada>("/Pessoa/GetComprovanteRetiradaById?id=" + idComprovante);
            if (response.StatusCode == System.Net.HttpStatusCode.OK)
            {
                dto = JsonConvert.DeserializeObject<ComprovanteRetirada>(response.Content);

                dto.IdUsuarioAlteracao = SessionManager.usuarioLogado.Id;


                //dto.FlagComputado = !fReprovado;
                dto.IdStatus = Domain.Enuns.EnumStatusCarteira.Aguardando;

                if (idStatus == 2)
                    dto.IdStatus = Domain.Enuns.EnumStatusCarteira.Inativo;
                if (idStatus == 5)
                    dto.IdStatus = Domain.Enuns.EnumStatusCarteira.Aguardando;
                if (idStatus == 6)
                    dto.IdStatus = Domain.Enuns.EnumStatusCarteira.Aprovado;
                if (idStatus == 8)
                    dto.IdStatus = Domain.Enuns.EnumStatusCarteira.Processando;



                //atualizar entrada do comprovante
                response = await PutObjectRestAsync<ComprovanteRetirada>("/Pessoa/UpdateComprovanteRetirada", dto);
                if (response.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    if (response.Content == null)
                    {
                        retorno.statusRetorno = ErrorMessageHttp.GetErrorMessage(System.Net.HttpStatusCode.GatewayTimeout);
                    }
                    else
                    {
                        retorno.statusRetorno = ErrorMessageHttp.GetErrorMessage(response.StatusCode);
                    }
                }
                else
                {
                    retorno.statusRetorno = ErrorMessageHttp.GetErrorMessage(response.StatusCode);
                }



                return Json(retorno, JsonRequestBehavior.AllowGet);
            }
            else
            {
                retorno.statusRetorno = ErrorMessageHttp.GetErrorMessage(response.StatusCode);

                return Json(retorno, JsonRequestBehavior.AllowGet);
            }
        }

        public async Task<ActionResult> AnexarComprovanteRetirada(int id)
        {

            try
            {

                //capturar comprovante by id
                var dto = new ComprovanteRetirada();
                IRestResponse response = await PostRestAsync<ComprovanteRetirada>("/Pessoa/GetComprovanteRetiradaById?id=" + id);
                if (response.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    dto = JsonConvert.DeserializeObject<ComprovanteRetirada>(response.Content);
                    retorno.statusRetorno = ErrorMessageHttp.GetErrorMessage(response.StatusCode);
                    retorno.objetoRetorno = dto;

                    return View(retorno);

                }
                else
                {
                    retorno.statusRetorno = ErrorMessageHttp.GetErrorMessage(response.StatusCode);
                    retorno.objetoRetorno = null;

                    return View(retorno);
                }

                retorno.statusRetorno = ErrorMessageHttp.GetErrorMessage(System.Net.HttpStatusCode.ExpectationFailed);


                return View(retorno);
            }
            catch (Exception ex)
            {

                throw;
            }

        }
        public async Task<ActionResult> ComprovanteCliente(int id)
        {

            try
            {

                //capturar comprovante by id
                var dto = new ComprovanteRetirada();
                IRestResponse response = await PostRestAsync<ComprovanteRetirada>("/Pessoa/GetComprovanteRetiradaById?id=" + id);
                if (response.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    dto = JsonConvert.DeserializeObject<ComprovanteRetirada>(response.Content);
                    retorno.statusRetorno = ErrorMessageHttp.GetErrorMessage(response.StatusCode);
                    retorno.objetoRetorno = dto;

                    return View("AnexarComprovanteRetiradaCliente", retorno);

                }
                else
                {
                    retorno.statusRetorno = ErrorMessageHttp.GetErrorMessage(response.StatusCode);
                    retorno.objetoRetorno = null;

                    return View("AnexarComprovanteRetiradaCliente", retorno);
                }

                retorno.statusRetorno = ErrorMessageHttp.GetErrorMessage(System.Net.HttpStatusCode.ExpectationFailed);


                return View("AnexarComprovanteRetiradaCliente", retorno);
            }
            catch (Exception ex)
            {

                throw;
            }

        }

        [HttpPost]
        public async Task<FineUploaderResult> UploadFileWithdraw(FineUpload upload, string idComprovante, string dt)
        {
            // asp.net mvc will set extraParam1 and extraParam2 from the params object passed by Fine-Uploader
            string meioPath = @"Image\ImagemComprovantesWithdraw\Carteira_" + SessionManager.usuarioLogado._Carteira.Id + @"\Comprovante_" + idComprovante;
            string meioPathIIS = @"Image/ImagemComprovantesWithdraw/Carteira_" + SessionManager.usuarioLogado._Carteira.Id + @"/Comprovante_" + idComprovante;

            var dir = System.Configuration.ConfigurationManager.AppSettings["localPath"] + meioPath;
            var dirIIS = System.Configuration.ConfigurationManager.AppSettings["localPathIIS"] + meioPathIIS + "/" + upload.Filename;

            var filePath = Path.Combine(dir, upload.Filename);

            try
            {
                upload.SaveAs(filePath);
                ResizeJpg(dir + @"\" + upload.Filename, 800, 600);



                //capturar comprovante by id
                var dto = new ComprovanteRetirada();
                IRestResponse response = await PostRestAsync<ComprovanteRetirada>("/Pessoa/GetComprovanteRetiradaById?id=" + idComprovante);
                if (response.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    dto = JsonConvert.DeserializeObject<ComprovanteRetirada>(response.Content);

                    dto.ComprovantePathLocation = meioPath + "/" + upload.Filename;
                    dto.ComprovantePathLocationIIS = meioPathIIS + "/" + upload.Filename;
                    dto.IdUsuarioAlteracao = SessionManager.usuarioLogado.Id;
                    dto.IdStatus = EnumStatusCarteira.Aprovado;
                    dto.FlagPendente = false;
                    dto.FlagComputado = true;
                    dto.DtAlteracao =Convert.ToDateTime( dt);

                    //atualizar entrada do comprovante
                    response = await PutObjectRestAsync<ComprovanteRetirada>("/Pessoa/UpdateComprovanteRetirada", dto);
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        if (response.Content == null)
                        {
                            return new FineUploaderResult(false, error: "Erro ao atualizar as entradas de registro do comprovante - 2!");
                        }

                    }
                    else
                    {
                        return new FineUploaderResult(false, error: "Não foi possivel acessar o método de update - 2!");
                    }

                }
                else
                {
                    return new FineUploaderResult(false, error: "Não foi possivel acessar o método de captura! - 1!");

                }



            }
            catch (Exception ex)
            {
                return new FineUploaderResult(false, error: ex.Message);
            }

            // the anonymous object in the result below will be convert to json and set back to the browser
            return new FineUploaderResult(true, new { extraInformation = 12345 });
        }

backend/Presentation/Views/Investimento/AnexarComprovanteRetiradaCliente.cshtml
@model Presentation.Helpers.ResponseJson
@{
    ViewBag.Title = "Index";
    Domain.Entities._2BTrust.ComprovanteRetirada dto = Model.objetoRetorno;

    string localPathIIS = System.Web.Configuration.WebConfigurationManager.AppSettings["localPathIIS"];

}
<link href="~/assets/fine-uploader/fine-uploader-gallery.css" rel="stylesheet" />
<link href="~/assets/fine-uploader/fine-uploader.css" rel="stylesheet" />
<script src="~/assets/fine-uploader/fine-uploader.core.js"></script>
<script src="~/assets/fine-uploader/fine-uploader.js"></script>
<script src="~/assets/fine-uploader/jquery.fine-uploader.js"></script>

<link href="~/assets/css/plugins/slick/slick.css" rel="stylesheet">
<link href="~/assets/css/plugins/slick/slick-theme.css" rel="stylesheet">
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Transfer</h2>
        <ol class="breadcrumb">
            <li>
                <a href="../Home">Home</a>
            </li>
            <li>
                <a>Transfer</a>
            </li>
            <li>
                <a href="../Carteira/Retirada">Withdraw</a>
            </li>
            <li class="active">
                <strong>Attached</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>


@if (Model.statusRetorno != "success")
{
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>Transaction</h5>
                        <div class="ibox-tools">

                        </div>
                    </div>
                    <div class="ibox-content">

                        <span> @Model.statusRetorno</span>

                    </div>
                </div>
            </div>
        </div>
    </div>



}
else
{
    <div class="wrapper wrapper-content animated fadeInRight">


        <div id="dvAnexos" class="animated pulse">
            @using (Html.BeginForm("AnexarComprovanteRetirada", "Investimento", FormMethod.Post, new { id = "fmDepositar", @autocomplete = "off", @enctype = "multipart/form-data" }))
            {
                <div class="row wrapper border-bottom white-bg page-heading">
                    <div class="col-lg-12">
                        <div class="row">
                            <div class="col-lg-9"><h2>Transaction #@dto.Id</h2> </div>
                            <div class="col-lg-3" style=" margin-top: 20px;">
                                <button class="btn btn-danger " style="float:right" type="button" id="btnCancelar" onclick="btnVoltar()">  Back </button>
                            </div>
                        </div>                       
                      
                        <hr />
                        <div class="row">
                            <div class="col-lg-3">
                                <div class="form-group">
                                    <h3>Transaction date</h3>
                                    <h4 style="color:#9a1b1b">@dto.DtInclusao.ToString("MM/dd/yyyy - HH:mm:ss")</h4>
                                </div>
                            </div>
                            <div class="col-lg-3">
                                <div class="form-group">
                                    <h3>Amount</h3>
                                    <h4 style="color:#9a1b1b">@dto.Valor.ToString("c").Replace("R$", "US$")</h4>
                                </div>
                            </div>
                        </div>
                    </div>

                    @{

                if (!string.IsNullOrEmpty(dto.ComprovantePathLocation))
                {

                    <div class="row">
                        <div class="col-lg-12">
                            <div class="form-group">
                                <hr />
                                <h3> Attached trasnfer or deposit!</h3>
                            </div>
                        </div>
                    </div>
                        <div class="row">
                            <div class="col-lg-12">
                                <img src="@localPathIIS@dto.ComprovantePathLocationIIS" />
                            </div>
                        </div>
                }
                else
                {

                  
                }

                    }

                </div>


            }

        </div>

    </div>

}

<script>

    function btnVoltar()
    {
        window.location='../Carteira/Retirada'
    }
   

</script>

backend/Presentation/Views/Investimento/Ativos.cshtml
@model Presentation.Helpers.ResponseJson
@{
    var iContador = 0;
    ViewBag.Title = "Index";
    List<Presentation.Models._2BTrustModel.BensImagensModel> listaImagem = new List<Presentation.Models._2BTrustModel.BensImagensModel>();
}
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Investment</h2>
        <ol class="breadcrumb">
            <li>
                <a href="../Home">Home</a>
            </li>
            <li class="active">
                <a>Investments</a>
            </li>
            @*<li class="active">
                <strong>Active</strong>
            </li>*@
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>


@if (Model.statusRetorno != "success")
{
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>Listagem de Produtos para Investir</h5>
                        <div class="ibox-tools">

                        </div>
                    </div>
                    <div class="ibox-content">

                        <span> @Model.statusRetorno</span>

                    </div>
                </div>
            </div>
        </div>
    </div>



}
else
{
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">


            @foreach (var itemPOOL in (IEnumerable<Presentation.Models._2BTrustModel.PoolBensPessoasModel>)Model.objetoRetorno)
            {

                if (itemPOOL.Cota > 0)
                {
                    iContador += 1;
                    var item = itemPOOL._PoolBens;
                    var imagemMostra = "";
                    Decimal valorTotal = 0;
                    Decimal valorCotas = 0;
                    foreach (var itemBens in item._Bens)
                    {
                        valorTotal += Convert.ToDecimal(itemBens.CapitalInvestido.ToString());
                        listaImagem.AddRange(itemBens._Imagens);
                    }
                    if (listaImagem.Count() > 0)
                    {
                        Random aleatorio = new Random();
                        var iMax = listaImagem.Count() - 1;
                        int index = aleatorio.Next(0, iMax);
                        imagemMostra = listaImagem[index].PathLocationIIS;
                    }

                    var valorCota = itemPOOL._PoolBens._Bens.Sum(c => Convert.ToDecimal(c.CapitalInvestido)) / itemPOOL._PoolBens.Cotas;
                    valorCotas = itemPOOL.Cota * valorCota;

                <div class="col-md-4">
                    <div class="ibox">
                        <div class="ibox-content product-box">

                            <div class="product-imitation" style="padding:0px!important; height:200px">

                                <span class="middle">
                                    <img src="@item.PathLocationIIS" style="width:100%; height:200px">
                                </span>
                            </div>
                            <div class="product-desc">
                                @*<span class="product-price">

            </span>*@
                                <small class="text-muted"> </small>
                                <a href="#" class="product-name"> @item.Nome</a>



                                @*<div class="small m-t-xs">
               Você tem @itemPOOL.Cota cotas compradas para este Pool, totalizando @valorCotas.ToString("c").Replace("R$", "US$")
            </div>*@
                                <div class="m-t text-righ">
                                    <a href="../Investimento/DetalhePool?id=@item.Id&opn=1" class="btn btn-xs btn-outline btn-primary" style="padding: 5px;    width: 90px;    height: 30px;">Invest</a>

                                    <a href="../Investimento/DetalhePoolAtivo?id=@item.Id" class="btn btn-xs btn-outline btn-primary" style="padding: 5px;    width: 90px;    height: 30px;">View Details </a>

                                    <a href="../Investimento/DetalhePoolVenda?id=@item.Id" class="btn btn-xs btn-outline btn-primary" style="padding: 5px;    width: 90px;    height: 30px;">Withdraw </a>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                }
            }
            @{
                if (iContador == 0)
                { <div class="row">
                        <div class="col-lg-12" style="text-align:center">
                            <h2>You have no active investment</h2>
                        </div>
                    </div>
                }
            }

        </div>



    </div>

}

backend/Presentation/Views/Investimento/DetalhePoolAtivo.cshtml
@model Presentation.Helpers.ResponseJson
@{
    ViewBag.Title = "Index";
    var pool = (Presentation.Models._2BTrustModel.PoolBensModel)Model.objetoRetorno;

    //var valorCota = pool._Bens.Sum(c => Convert.ToDecimal(c.CapitalInvestido)) / pool.Cotas;
    var valorCota = 100;
}

<link href="../assets/css/plugins/slick/slick.css" rel="stylesheet">
<link href="../assets/css/plugins/slick/slick-theme.css" rel="stylesheet">

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>@pool.Nome - Portfolio</h2>
        <ol class="breadcrumb">
            <li>
                <a href="../Home">Home</a>
            </li>
            <li>
                <a>Investment</a>
            </li>
            <li class="active">
                <strong>Details</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>

@if (Model.statusRetorno != "success")
{
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>E</h5>
                        <div class="ibox-tools">

                        </div>
                    </div>
                    <div class="ibox-content">

                        <span> @Model.statusRetorno</span>

                    </div>
                </div>
            </div>
        </div>
    </div>



}
else
{

    <div class="wrapper wrapper-content animated fadeInRight">



        <div class="row" id="dvContent">

            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title" style=" padding: 7px;">

                        <div class="col-lg-8"> <h5><b>@pool.Nome - Portfolio</b></h5> </div>

                        @*<div class="col-lg-3" style="">
                            <button class="btn btn-primary center-block" type="button" id="btnVisaoGeral" onclick="btnVisaoGeral()"> Overview</button>
                        </div>*@

                        <div class="col-lg-4" style="">
                            <button class="btn btn-danger " style="float:right" type="button" id="btnCancelar" onclick="btnVoltar()"> Back</button>
                        </div>
                    </div>
                    <div class="ibox-content">


                        <div class="row">
                            <div class="col-lg-12">
                                @foreach (var item in pool._Bens)
                                {

                                    <div class="row animated pulse" style="border: 1px solid #d0d0d0; margin: 15px; padding: 10px; box-shadow: -2px 2px 7px 1px #cecece;">
                                        <div class="col-md-5">


                                            <div class="product-images">

                                                @foreach (var itemImage in item._Imagens)
                                                {
                                                    <div>
                                                        <div class="image-imitation" style="padding:0px!important">
                                                            <img src="@itemImage.PathLocationIIS" style="width:100%" />
                                                        </div>
                                                    </div>
                                                }

                                            </div>

                                        </div>
                                        <div class="col-md-7">

                                            <h2 class="font-bold m-b-xs">
                                                @item.Nome
                                            </h2>
                                            <div class="m-t-md">
                                                <h2 class="product-main-price">
                                                    U$ @Convert.ToDecimal(item.CapitalInvestido.ToString()).ToString("#,##0.00")
                                                    @*<small class="text-muted">Capital Investido</small>*@
                                                </h2>
                                            </div>
                                            <hr>

                                            <h4>
                                                Description
                                            </h4>

                                            <div class="small text-muted">
                                                @item.Descritivo
                                            </div>
                                            <dl class="small m-t-md">
                                                <dt>Performance</dt>
                                                <dd>@Convert.ToDecimal(item.performance).ToString("#,##0.00")% </dd>
                                                <dt>Acquisition</dt>
                                                <dd>@item.DtInclusao.ToString("MM/dd/yyyy")</dd>
                                                @*<dt>Data Vigência</dt>
                                                    <dd>@item._Rentabilidade.DtFim.ToString("MM/dd/yyyy")</dd>*@
                                            </dl>


                                            <hr>




                                        </div>
                                    </div>


                                }
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>



    </div>

}

<script>



    console.clear();

    function btnSolicitar() {
        var valorSolicitado = $("#mValorCotas").val();


        swal({
            title: "Atenção",
            text: "Deseja solicitar entrada neste investimento no valor de US$ " + valorSolicitado + " ?",
            type: "warning",
            showCancelButton: true,
            confirmButtonClass: "btn-danger",
            confirmButtonText: "Sim",
            cancelButtonText: "Não",
            closeOnConfirm: false
        }).then((result) => {

    var form = $("#fmSolicitarEntrada");
    showLoading("Efetuando solicitação e entrada...");
    $.ajax({
        url: '../Investimento/SolicitarEntradaPool',
        type: 'POST',
        data: form.serialize(),
        beforeSend: function () {

        },
        onsuccess: function () { },
        success: function (result) {
            hideLoading();
            if (result.statusRetorno == 'success') {

                swal({
                    title: "Sucesso",
                    text: "Sua entrada foi realizada com sucesso! Você receberá um email com a confirmção. Você também pode acompanhar os lançamentos em sua dashboard!",
                    type: "success",
                    showCancelButton: false,
                    confirmButtonText: "OK",
                    closeOnConfirm: false
                }).then((result) => {

    window.location = '../Home'
});

            }
            else {
                hideLoading();
                swal("Atenção", result.statusRetorno, "error");
            }
        }
    });

});




    }

     function btnVisaoGeral() {
         showLoading("Overview", 'Loading...');
         window.location = '../BensVisaoGeral/OverView';
    }

    function btnVoltar() {
        showLoading("One Moment Please",'Loading...');
        window.location = '../Investimento/Ativos';
    }


    function fnChangeCotas(obj) {
        var qntCotas = $(obj).val() + ".00";
        var valorCotas = parseFloat(qntCotas) * parseFloat('@valorCota.ToString().Replace(',','.')').toFixed(2);
        $("#mValorCotas").val(parseFloat(valorCotas).toFixed(2).replace(/(\d)(?=(\d{3})+\.)/g, "$1,").toString().replace(',', '-').replace('.', ',').replace('-', '.'));
        $("#valorCotaAdq").html("US$ " + parseFloat(valorCotas).toFixed(2).replace(/(\d)(?=(\d{3})+\.)/g, "$1,").toString().replace(',', '-').replace('.', ',').replace('-', '.'))

    }
    function btnAderir() {
        $(".touchspin3").TouchSpin({
            verticalbuttons: true,
            buttondown_class: 'btn btn-white',
            buttonup_class: 'btn btn-white',
            max: '@pool.CotasDisponiveis'
        });
        $("#dvContent").removeClass('col-lg-12');
        $("#dvContent").addClass('col-lg-9');
        $("#btnAderir").fadeOut();
        $("#btnCancelar").fadeIn();

        $("#dvAderir").fadeIn();
    }

    function btnCancelar() {
        $("#dvContent").removeClass('col-lg-9');
        $("#dvContent").addClass('col-lg-12');
        $("#btnAderir").fadeIn();
        $("#btnCancelar").fadeOut();

        $("#dvAderir").fadeOut();
    }

    function btnSelecionar() {

        var idInvestidorManual = $("#idInvestidorManual").val();
        if (idInvestidorManual == '' || idInvestidorManual == 0) {
            swal("Atenção", "É necessário selecionar um investidor para esta opção!", "error");
        }
        else {

            showLoading("One Moment Please",'Loading...');
            window.location = '../Investimento/DetalhePool?id=@pool.Id&m=' + idInvestidorManual;
        }


    }
    window.onload = function (event) {
        $('.product-images').slick({
            dots: true
        });
        $("[Name='idInvestidorManual']").select2({
            placeholder: " ",
            allowClear: true
        });

    };

</script>