backend/Presentation/Controllers/AreasController.cs
using AutoMapper;
using Domain.Entities._2BTrust;
using Newtonsoft.Json;
using Presentation.Helpers;
using Presentation.Models._2BTrustModel;
using RestSharp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace Presentation.Controllers
{
    public class AreasController : BaseController
    {
        // GET: Areas
        public async Task<ActionResult> Index()
        {
            try
            {
                IEnumerable<AreasModel> model;

                

                IRestResponse response = await PostRestAsync<Areas>("/Areas/GetListAreas");
                if (response.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    model = JsonConvert.DeserializeObject<IEnumerable<AreasModel>>(response.Content);

                    retorno.statusRetorno = ErrorMessageHttp.GetErrorMessage(response.StatusCode);
                    retorno.objetoRetorno = model;


                    return View(retorno);

                }
                else
                {
                    retorno.statusRetorno = ErrorMessageHttp.GetErrorMessage(response.StatusCode);
                    retorno.objetoRetorno = null;

                    return View(retorno);
                }

                retorno.statusRetorno = ErrorMessageHttp.GetErrorMessage(System.Net.HttpStatusCode.ExpectationFailed);


                return View(retorno);
            }
            catch (Exception ex)
            {

                throw;
            }
            return View();
        }


        public async Task<ActionResult> Area(int? idArea)
        {
            try
            {
                if (idArea == null)
                {
                    var modelInsert = new AreasModel()
                    {
                        IdUsuarioInclusao = SessionManager.usuarioLogado._Usuario.Id,
                        FlgAtivo = true,
                        Id = 0
                    };


                    return View(modelInsert);
                }

                var model = new AreasModel();
                

                IRestResponse response = await PostRestAsync<Areas>("/Areas/GetAreasById?idArea=" + idArea);
                if (response.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    model = JsonConvert.DeserializeObject<AreasModel>(response.Content);


                    return View(model);

                }
                else
                {
                    var modelInsert = new AreasModel()
                    {
                        IdUsuarioInclusao = SessionManager.usuarioLogado._Usuario.Id,
                        FlgAtivo = true,
                        Id = 0
                    };

                    return View(modelInsert);
                }

            }
            catch (Exception ex)
            {

                throw;
            }
        }

        [HttpPost]
        public async Task<ActionResult> Area(AreasModel model)
        {

            try
            {
                if (ModelState.IsValid)
                {
                    string sLocation = "/Areas/InsertAreas";
                    var dto = Mapper.Map<Areas>(model);
                    if (dto.Id > 0) sLocation = "/Areas/EditAreas";

                    

                    IRestResponse response = await PutObjectRestAsync<Areas>(sLocation, dto);
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        if (response.Content != null)
                        {

                            dto = JsonConvert.DeserializeObject<Areas>(response.Content);
                            retorno.statusRetorno = ErrorMessageHttp.GetErrorMessage(response.StatusCode);
                            retorno.objetoRetorno = dto;

                        }
                        else
                        {
                            retorno.statusRetorno = ErrorMessageHttp.GetErrorMessage(System.Net.HttpStatusCode.ExpectationFailed);
                            retorno.objetoRetorno = null;
                        }

                        return Json(retorno, JsonRequestBehavior.AllowGet);
                    }
                    else
                    {
                        retorno.statusRetorno = ErrorMessageHttp.GetErrorMessage(System.Net.HttpStatusCode.ExpectationFailed);
                        retorno.objetoRetorno = null;
                        return Json(retorno, JsonRequestBehavior.AllowGet);
                    }
                }
                else
                {
                    retorno.statusRetorno = "Verifique a validação dos campos!";
                    return Json(retorno, JsonRequestBehavior.AllowGet);
                }



            }
            catch (Exception ex)
            {
                retorno.statusRetorno = ErrorMessageHttp.GetErrorMessage(System.Net.HttpStatusCode.ExpectationFailed);
                retorno.objetoRetorno = null;
                return Json(retorno, JsonRequestBehavior.AllowGet);
            }
        }

        private async Task<bool> EditArea(Areas area)
        {
            try
            {
                var dto = new Areas();
                

                IRestResponse response = await PutObjectRestAsync<Areas>("/Areas/EditAreas", area);
                if (response.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    if (response.Content != null)
                    {
                        return true;
                    }

                    return true;
                }
                else
                {
                    return false;

                }
            }
            catch (Exception ex)
            {

                return false;
            }
        }


        [HttpPost]
        public async Task<ActionResult> Ativar(int idArea)
        {
            try
            {
                //buscar area 
                var dto = new Areas();
                

                IRestResponse response = await PostRestAsync<Areas>("/Areas/GetAreasById?idArea=" + idArea);
                if (response.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    dto = JsonConvert.DeserializeObject<Areas>(response.Content);

                    retorno.statusRetorno = ErrorMessageHttp.GetErrorMessage(response.StatusCode);
                    retorno.objetoRetorno = dto;

                    dto.FlgAtivo = true;

                    // ativar (UPDATE__
                    var fUpdate = await EditArea(dto);

                    if (!fUpdate)
                    {

                        retorno.statusRetorno = ErrorMessageHttp.GetErrorMessage(System.Net.HttpStatusCode.ExpectationFailed);
                        retorno.objetoRetorno = null;
                    }

                    return Json(retorno, JsonRequestBehavior.AllowGet);

                }
                else
                {
                    retorno.statusRetorno = ErrorMessageHttp.GetErrorMessage(response.StatusCode);
                    retorno.objetoRetorno = null;

                    return Json(retorno, JsonRequestBehavior.AllowGet);
                }

            }
            catch (Exception ex)
            {

                throw;
            }
        }

        [HttpPost]
        public async Task<ActionResult> Desativar(int idArea)
        {
            try
            {
                //buscar area 
                var dto = new Areas();
                

                IRestResponse response = await PostRestAsync<Areas>("/Areas/GetAreasById?idArea=" + idArea);
                if (response.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    dto = JsonConvert.DeserializeObject<Areas>(response.Content);

                    retorno.statusRetorno = ErrorMessageHttp.GetErrorMessage(response.StatusCode);
                    retorno.objetoRetorno = dto;

                    dto.FlgAtivo = false;

                    // ativar (UPDATE__
                    var fUpdate = await EditArea(dto);

                    if (!fUpdate)
                    {

                        retorno.statusRetorno = ErrorMessageHttp.GetErrorMessage(System.Net.HttpStatusCode.ExpectationFailed);
                        retorno.objetoRetorno = null;
                    }


                    return Json(retorno, JsonRequestBehavior.AllowGet);

                }
                else
                {
                    retorno.statusRetorno = ErrorMessageHttp.GetErrorMessage(response.StatusCode);
                    retorno.objetoRetorno = null;


                    return Json(retorno, JsonRequestBehavior.AllowGet);
                }

            }
            catch (Exception ex)
            {

                throw;
            }
        }






    }
}

backend/Presentation/Views/Controles/Controle.cshtml
@model Presentation.Models._2BTrustModel.ControlesModel
@{
    ViewBag.Title = "Controles";
}
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Áreas</h2>
        <ol class="breadcrumb">
            <li>
                <a href="../Home">Home</a>
            </li>
            <li>
                <a>Administrativo</a>
            </li>
            <li>
                <a href="../Controles">Menus</a>
            </li>
            <li class="active">
                <strong>Cadastro Menu</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>


<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Menu do Sistema</h5>
                    <div class="ibox-tools">
                        <button class="btn btn-success  dim" type="button" id="btnSalvar" onclick="btnSalvar()"><i class="fa fa-add"> Salvar</i></button>
                    </div>
                </div>
                <div class="ibox-content">
                    @{Html.RenderPartial("_loading");}
                    @using (Html.BeginForm("Area", "Areas", FormMethod.Post, new { id = "fmControle", @autocomplete = "off" }))
                    {

                        @Html.AntiForgeryToken()
                        @Html.HiddenFor(c => c.IdUsuarioInclusao)
                        @Html.HiddenFor(c => c.Id)
                        @Html.HiddenFor(c => c.IdUsuarioAlteracao)
                        @Html.HiddenFor(c => c.FlagAtivo)


                        <div class="row">

                            <div class="col-lg-1">
                                <label>#</label><br />
                                <label>@Model.Id</label>
                            </div>

                            <div class="col-lg-2">
                                <div class="form-group">
                                    <label>Código *</label>
                                    @Html.TextBoxFor(m => m.Codigo, new { @class = "form-control required", @placeholder = "Digite o código" })
                                    @Html.ValidationMessageFor(c => c.Codigo)
                                </div>
                            </div>
                            <div class="col-lg-4">
                                <div class="form-group">
                                    <label>Nome *</label>
                                    @Html.TextBoxFor(m => m.Nome, new { @class = "form-control required", @placeholder = "Digite o nome" })
                                    @Html.ValidationMessageFor(c => c.Nome)
                                </div>
                            </div>
                            <div class="col-lg-5">
                                <div class="form-group">
                                    <label>Área *</label>
                                    @Html.DropDownListFor(m => m.IdArea, new SelectList(ViewBag.Areas, "Id", "Nome", 0), "", new { @class = "form-control select2 required", @style = "width:100%;" })
                                    @Html.ValidationMessageFor(c => c.IdArea)
                                </div>
                            </div>

                        </div>


                        <div class="row">

                            <div class="col-lg-12">
                                <div class="form-group">
                                    <label>Caso o menu que está sendo cadastrado seja um sub-menu, favor selecionar qual o Menu Pai</label>
                                    @Html.DropDownListFor(m => m.IdControlePrincipal, new SelectList(ViewBag.MeuPai, "Id", "Nome", 0), "", new { @class = "form-control select2 ", @style = "width:100%;" })
                                    @Html.ValidationMessageFor(c => c.IdControlePrincipal)
                                </div>
                            </div>

                        </div>


                        <div class="row">

                            <div class="col-lg-3">
                                <div class="form-group">
                                    <label>Url Controller *</label>
                                    @Html.TextBoxFor(m => m.UrlController, new { @class = "form-control required", @placeholder = "Digite o código" })
                                    @Html.ValidationMessageFor(c => c.UrlController)
                                </div>
                            </div>

                            <div class="col-lg-3">
                                <div class="form-group">
                                    <label>Icone Menu </label>
                                    @Html.TextBoxFor(m => m.iconLI, new { @class = "form-control", @placeholder = "Ex: fa fa-bell" })
                                    @Html.ValidationMessageFor(c => c.iconLI)
                                </div>
                            </div>

                            <div class="col-lg-3">
                                <div class="form-group">
                                    <label>ID Menu Principal </label>
                                    @Html.TextBoxFor(m => m.idJqueryPai, new { @class = "form-control", @placeholder = "Ex: menu1..." })
                                    @Html.ValidationMessageFor(c => c.iconLI)
                                </div>
                            </div>

                            <div class="col-lg-3">
                                <div class="form-group">
                                    <label>ID Menu Secundário </label>
                                    @Html.TextBoxFor(m => m.idJqueryFilho, new { @class = "form-control", @placeholder = "Ex: mnExemplo" })
                                    @Html.ValidationMessageFor(c => c.iconLI)
                                </div>
                            </div>


                            <div class="col-lg-4">
                                <div class="form-group">
                                    <label>Nome da Controller </label>
                                    @Html.TextBoxFor(m => m.Controller, new { @class = "form-control", @placeholder = "Ex: mnExemplo" })
                                    @Html.ValidationMessageFor(c => c.Controller)
                                </div>
                            </div>

                            @*<div class="col-lg-6">
                                <div class="form-group">
                                    <label>Escolha as ações que podem ser usadas </label>

                                    @for (int idx = 0; idx < Model._Acoes.Count(); idx++)
                                    {
                                        @Html.HiddenFor(x => Model._Acoes[idx].Id)
                                        @Html.HiddenFor(x => Model._Acoes[idx].Nome)
                                        @Html.HiddenFor(x => Model._Acoes[idx].Codigo)
                                        @Html.HiddenFor(x => Model._Acoes[idx].Id)

                                        var strID = "chk" + idx;
                                        <div class="row">

                                            <div class="col-lg-2">
                                                <div class="switch">
                                                    <div class="onoffswitch">
                                                        @Html.CheckBoxFor(x => Model._Acoes[idx].FlgAtivo, new { @class = "", @id = strID })
                                                        
                                                        @*<label class="onoffswitch-label" for='@strID'>
                                                            <span class="onoffswitch-inner"></span>
                                                            <span class="onoffswitch-switch"></span>
                                                        </label 
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-lg-5"><span>@Model._Acoes[idx].Nome</span></div>

                                        </div>

                                    } 
                                </div>
                            </div>*@


                        </div>

                    }
                </div>
            </div>
        </div>
    </div>
</div>



<script>
    console.clear();

    $(document).ready(function () {


    });

    function btnSalvar() {

        var form = $("#fmControle");

        if (form.valid() == false) {
            swal("Atenção", "Verifique a validação dos campos!", "error");
            return false;
        }
        else {

            showLoading("Salvando Informações");
            $.ajax({
                url: '../Controles/Controle',
                type: 'POST',
                data: form.serialize(),
                beforeSend: function () {

                },
                onsuccess: function () { },
                success: function (result) {
                    if (result.statusRetorno == 'success') {

                        swal("Perfeito", "Cadastro realizado com sucesso!", "success");

                        setTimeout(function () {
                            window.location = "../Controles";
                        }, 2500);

                    }
                    else {
                        hideLoading();
                        swal("Atenção", "Ocorreu um erro ao efetuar seu cadastro! Tente novamente", "error");
                    }
                }
            });
        }
    };

</script>

backend/Presentation/Views/Controles/Index.cshtml
@model Presentation.Helpers.ResponseJson
@{
    ViewBag.Title = "Index";

    IEnumerable<Presentation.Models._2BTrustModel.ControlesModel> listModel = (IEnumerable<Presentation.Models._2BTrustModel.ControlesModel>)Model.objetoRetorno;


    var grpOrderedYr = listModel.GroupBy(
   areas => areas._Area.Nome).OrderBy(areas => areas.Key);




}
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Áreas</h2>
        <ol class="breadcrumb">
            <li>
                <a href="../Home">Home</a>
            </li>
            <li>
                <a>Administrativo</a>
            </li>
            <li class="active">
                <strong>Menus</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>


@if (Model.statusRetorno != "success")
{
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>Listagem de Menus do Sistema</h5>
                        <div class="ibox-tools">

                        </div>
                    </div>
                    <div class="ibox-content">

                        <span> @Model.statusRetorno</span>

                    </div>
                </div>
            </div>
        </div>
    </div>



}
else
{

    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>Listagem de Menus do Sistema</h5>
                        <div class="ibox-tools">
                            <button class="btn btn-success  dim" id="btnNovo" onclick="btnNovo()" type="button"><i class="fa fa-plus"> Novo</i></button>
                        </div>
                    </div>
                    <div class="ibox-content">

                        <div class="table-responsive">

                            @foreach (var areas in grpOrderedYr)
                            {
                                <div class="row">
                                    <div class="col-lg-12" style=" padding: 20px; ">
                                        <span style="    font-size: 20px;    text-decoration: underline">@areas.Key</span><br />
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-lg-12">
                                        <table class="table table-striped table-bordered table-hover dataTables-example">
                                            <thead>
                                                <tr>
                                                    <th>#</th>
                                                    <th>Área</th>
                                                    <th>Nome</th>
                                                    <th>Nível</th>
                                                    <th>Data Inclusão</th>
                                                    <th>Opções</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @foreach (var item in areas)
                                                {


                                                    <tr class="gradeX">

                                                        <td>@item.Id</td>
                                                        <td>@item._Area.Nome</td>
                                                        <td>@item.Nome</td>
                                                        @if (item.IdControlePrincipal == null || item.IdControlePrincipal == 0)
                                                        {
                                                            <td><span>Principal</span></td>
                                                        }
                                                        else
                                                        {
                                                            <td><span>Secundário</span></td>
                                                        }
                                                        <td>@item.DtInclusao.ToString("MM/dd/yyyy")</td>
                                                        <td>
                                                            <button class="btn btn-info " type="button" onclick="btnEdit('@item.Id')"><i class="fa fa-paste"></i> Editar</button>
                                                            @if (item.FlagAtivo == true)
                                                            {
                                                                <button class="btn btn-danger " onclick="btnDeletar('@item.Id')" type="button" idcontrole="@item.Id"><i class="fa fa-wrench"></i> Deletar</button>
                                                            }
                                                            else
                                                            {
                                                                <button class="btn btn-success " onclick="btnAtivar('@item.Id')" type="button" idcontrole="@item.Id"><i class="fa fa-check"></i> Ativar</button>
                                                            }
                                                        </td>

                                                    </tr>
                                                }
                                            </tbody>
                                        </table>

                                    </div>
                                </div>
                                
                                <hr />
                            }

                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
}

<script>





    function btnEdit(idCOntrole) {
        showLoading('Acessando...');
        window.location = '../Controles/Controle?idControle=' + idCOntrole
    }

    function btnNovo() {
        showLoading('Acessando...');
        window.location = '../Controles/Controle'
    }

    function btnAtivar(idControle) {

        showLoading('Processando...');
        $.ajax({
            url: '../Controles/Ativar',
            type: 'POST',
            data: { idControle: idControle },
            beforeSend: function () {

            },
            onsuccess: function () { },
            success: function (result) {
                if (result.statusRetorno == 'success') {
                    hideLoading();
                    swal("Perfeito", "Item ativado com sucesso!", "success");

                    setTimeout(function () {
                        window.location = "../Controles";
                    }, 2000);

                }
                else {
                    hideLoading();
                    swal("Atenção", result.statusRetorno, "error");
                }
            }
        });

    }

    function btnDeletar(idControle) {

        showLoading('Processando...');
        $.ajax({
            url: '../Controles/Desativar',
            type: 'POST',
            data: { idControle: idControle },
            beforeSend: function () {

            },
            onsuccess: function () { },
            success: function (result) {
                if (result.statusRetorno == 'success') {
                    hideLoading();
                    swal("Perfeito", "Item deletado com sucesso!", "success");

                    setTimeout(function () {
                        window.location = "../Controles";
                    }, 2000);

                }
                else {
                    hideLoading();
                    swal("Atenção", result.statusRetorno, "error");
                }
            }
        });

    }

</script>