backend/Presentation/Controllers/ContratosController.cs
using ApplicationServices.IApplicationServices;
using AutoMapper;
using Domain.Entities._2BTrust;
using Newtonsoft.Json;
using Presentation.Helpers;
using Presentation.Models._2BTrustModel;
using RestSharp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Presentation.Controllers
{
    public class ContratosController : BaseController
    {
        // GET: Contratos
        public async Task<ActionResult> Index()
        {

            try
            {


                IEnumerable<ContratosModel> model;


                IRestResponse response = await PostRestAsync<Contratos>("/Contratos/GetListContratos");
                if (response.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    model = JsonConvert.DeserializeObject<IEnumerable<ContratosModel>>(response.Content);

                    retorno.statusRetorno = ErrorMessageHttp.GetErrorMessage(response.StatusCode);
                    retorno.objetoRetorno = model;

                    return View(retorno);

                }
                else
                {
                    retorno.statusRetorno = ErrorMessageHttp.GetErrorMessage(response.StatusCode);
                    retorno.objetoRetorno = null;

                    return View(retorno);
                }

                retorno.statusRetorno = ErrorMessageHttp.GetErrorMessage(System.Net.HttpStatusCode.ExpectationFailed);


                return View(retorno);
            }
            catch (Exception ex)
            {

                throw;
            }

        }

        public async Task<ActionResult> Contrato(int? idContrato)
        {
            try
            {
                if (idContrato == null)
                {
                    var modelInsert = new ContratosModel()
                    {
                        IdUsuarioInclusao = SessionManager.usuarioLogado._Usuario.Id,
                        IdStatus = 1,
                        Id = 0
                    };


                    return View(modelInsert);
                }

                var model = new ContratosModel();
                IRestResponse response = await PostRestAsync<Contratos>("/Contratos/GetContratosById?idContrato=" + idContrato);
                if (response.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    model = JsonConvert.DeserializeObject<ContratosModel>(response.Content);


                    return View(model);

                }
                else
                {
                    var modelInsert = new ContratosModel()
                    {
                        IdUsuarioInclusao = SessionManager.usuarioLogado._Usuario.Id,
                        IdStatus = 1,
                        Id = 0
                    };

                    return View(modelInsert);
                }

            }
            catch (Exception ex)
            {

                throw;
            }
        }




        [HttpPost]
        public async Task<ActionResult> Contrato(ContratosModel model)
        {

            try
            {
                if (ModelState.IsValid)
                {
                    string sLocation = "/Contratos/InsertContrato";
                    var dto = Mapper.Map<Contratos>(model);
                    if (dto.Id > 0) sLocation = "/Contratos/EditContrato";


                    IRestResponse response = await PutObjectRestAsync<Contratos>(sLocation, dto);
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        if (response.Content != null)
                        {

                            dto = JsonConvert.DeserializeObject<Contratos>(response.Content);
                            retorno.statusRetorno = ErrorMessageHttp.GetErrorMessage(response.StatusCode);
                            retorno.objetoRetorno = dto;

                        }
                        else
                        {
                            retorno.statusRetorno = ErrorMessageHttp.GetErrorMessage(System.Net.HttpStatusCode.ExpectationFailed);
                            retorno.objetoRetorno = null;
                        }

                        return Json(retorno, JsonRequestBehavior.AllowGet);
                    }
                    else
                    {
                        retorno.statusRetorno = ErrorMessageHttp.GetErrorMessage(System.Net.HttpStatusCode.ExpectationFailed);
                        retorno.objetoRetorno = null;
                        return Json(retorno, JsonRequestBehavior.AllowGet);
                    }
                }
                else
                {
                    retorno.statusRetorno = "Verifique a validação dos campos!";
                    return Json(retorno, JsonRequestBehavior.AllowGet);
                }



            }
            catch (Exception ex)
            {
                retorno.statusRetorno = ErrorMessageHttp.GetErrorMessage(System.Net.HttpStatusCode.ExpectationFailed);
                retorno.objetoRetorno = null;
                return Json(retorno, JsonRequestBehavior.AllowGet);
            }
        }

        private async Task<bool> EditContrato(Contratos contrato)
        {
            try
            {
                var dto = new Areas();
                IRestResponse response = await PutObjectRestAsync<Contratos>("/Contratos/EditContrato", contrato);
                if (response.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    if (response.Content != null)
                    {
                        return true;
                    }

                    return true;
                }
                else
                {
                    return false;

                }
            }
            catch (Exception ex)
            {

                return false;
            }
        }


        [HttpPost]
        public async Task<ActionResult> Ativar(int idContrato)
        {
            try
            {
                //buscar contrato  
                var dto = new Contratos();
                IRestResponse response = await PostRestAsync<Contratos>("/Contratos/GetContratosById?idContrato=" + idContrato);
                if (response.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    dto = JsonConvert.DeserializeObject<Contratos>(response.Content);

                    retorno.statusRetorno = ErrorMessageHttp.GetErrorMessage(response.StatusCode);
                    retorno.objetoRetorno = dto;

                    dto.IdStatus = 1;

                    // ativar (UPDATE__
                    var fUpdate = await EditContrato(dto);

                    if (!fUpdate)
                    {

                        retorno.statusRetorno = ErrorMessageHttp.GetErrorMessage(System.Net.HttpStatusCode.ExpectationFailed);
                        retorno.objetoRetorno = null;
                    }

                    return Json(retorno, JsonRequestBehavior.AllowGet);

                }
                else
                {
                    retorno.statusRetorno = ErrorMessageHttp.GetErrorMessage(response.StatusCode);
                    retorno.objetoRetorno = null;

                    return Json(retorno, JsonRequestBehavior.AllowGet);
                }

            }
            catch (Exception ex)
            {

                throw;
            }
        }

        [HttpPost]
        public async Task<ActionResult> Desativar(int idContrato)
        {
            try
            {
                //buscar contrato 
                var dto = new Contratos();
                IRestResponse response = await PostRestAsync<Contratos>("/Contratos/GetContratosById?idContrato=" + idContrato);
                if (response.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    dto = JsonConvert.DeserializeObject<Contratos>(response.Content);

                    retorno.statusRetorno = ErrorMessageHttp.GetErrorMessage(response.StatusCode);
                    retorno.objetoRetorno = dto;

                    dto.IdStatus = 2;

                    // ativar (UPDATE__
                    var fUpdate = await EditContrato(dto);

                    if (!fUpdate)
                    {

                        retorno.statusRetorno = ErrorMessageHttp.GetErrorMessage(System.Net.HttpStatusCode.ExpectationFailed);
                        retorno.objetoRetorno = null;
                    }


                    return Json(retorno, JsonRequestBehavior.AllowGet);

                }
                else
                {
                    retorno.statusRetorno = ErrorMessageHttp.GetErrorMessage(response.StatusCode);
                    retorno.objetoRetorno = null;


                    return Json(retorno, JsonRequestBehavior.AllowGet);
                }

            }
            catch (Exception ex)
            {

                throw;
            }
        }






    }
}

backend/Presentation/Views/Contratos/Contrato.cshtml
@model Presentation.Models._2BTrustModel.ContratosModel
@{
    ViewBag.Title = "Controles";
}
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Contrato</h2>
        <ol class="breadcrumb">
            <li>
                <a href="../Home">Home</a>
            </li>
            <li>
                <a>Financeiro ADM</a>
            </li>
            <li>
                <a href="../Contratos">Menus</a>
            </li>
            <li class="active">
                <strong>Cadastro Contrato</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>


<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Contrato do Sistema</h5>
                    <div class="ibox-tools">
                        <button class="btn btn-success" type="button" id="btnSalvar" onclick="btnSalvar()"> Salvar</button>
                    </div>
                </div>
                <div class="ibox-content">
                    @{Html.RenderPartial("_loading");}
                    @using (Html.BeginForm("Contrato", "Contratos", FormMethod.Post, new { id = "fmContrato", @autocomplete = "off" }))
                    {

                        @Html.AntiForgeryToken()
                        @Html.HiddenFor(c => c.IdUsuarioInclusao)
                        @Html.HiddenFor(c => c.Id)
                        @Html.HiddenFor(c => c.IdUsuarioAlteracao)
                        @Html.HiddenFor(c => c.IdStatus)


                        <div class="row">

                            <div class="col-lg-1">
                                <label>#</label><br />
                                <label>@Model.Id</label>
                            </div>

                            <div class="col-lg-2">
                                <div class="form-group">
                                    <label>Código *</label>
                                    @Html.TextBoxFor(m => m.Codigo, new { @class = "form-control required", @placeholder = "Digite o código" })
                                    @Html.ValidationMessageFor(c => c.Codigo)
                                </div>
                            </div>
                            <div class="col-lg-9">
                                <div class="form-group">
                                    <label>Descrição *</label>
                                    @Html.TextBoxFor(m => m.Descricao, new { @class = "form-control required", @placeholder = "Digite o nome" })
                                    @Html.ValidationMessageFor(c => c.Descricao)
                                </div>
                            </div>


                        </div>
                        <div class="row">

                           
                            <div class="col-lg-offset-1 col-lg-3">
                                <div class="form-group">
                                    <label>Data Início *</label>
                                    @Html.TextBoxFor(m => m.DtInicio, new { @class = "form-control required date", @placeholder = " " })
                                    @Html.ValidationMessageFor(c => c.DtInicio)
                                </div>
                            </div>
                            <div class="col-lg-3">
                                <div class="form-group">
                                    <label>Data Vigência *</label>
                                    @Html.TextBoxFor(m => m.DtVigencia, new { @class = "form-control required date", @placeholder = " " })
                                    @Html.ValidationMessageFor(c => c.DtVigencia)
                                </div>
                            </div>


                        </div>





                    }
                </div>
            </div>
        </div>
    </div>
</div>



<script>
    console.clear();

    $(document).ready(function () {


    });

    function btnSalvar() {

        var form = $("#fmContrato");

        if (form.valid() == false) {
            swal("Atenção", "Verifique a validação dos campos!", "error");
            return false;
        }
        else {

            showLoading("Salvando Informações");
            $.ajax({
                url: '../Contratos/Contrato',
                type: 'POST',
                data: form.serialize(),
                beforeSend: function () {

                },
                onsuccess: function () { },
                success: function (result) {
                    if (result.statusRetorno == 'success') {

                        swal("Perfeito", "Cadastro realizado com sucesso!", "success");

                        setTimeout(function () {
                            window.location = "../Contratos";
                        }, 2500);

                    }
                    else {
                        hideLoading();
                        swal("Atenção", "Ocorreu um erro ao efetuar seu cadastro! Tente novamente", "error");
                    }
                }
            });
        }
    };

</script>

backend/Presentation/Views/Contratos/Index.cshtml
@model Presentation.Helpers.ResponseJson
@{
    ViewBag.Title = "Index";
}
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Contratos</h2>
        <ol class="breadcrumb">
            <li>
                <a href="../Home">Home</a>
            </li>
            <li>
                <a>Financeiro ADM</a>
            </li>
            <li class="active">
                <strong>Contratos</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>


@if (Model.statusRetorno != "success")
{
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>Listagem de Contratos do Sistema</h5>
                        <div class="ibox-tools">

                        </div>
                    </div>
                    <div class="ibox-content">

                        <span> @Model.statusRetorno</span>

                    </div>
                </div>
            </div>
        </div>
    </div>



}
else
{

    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>Listagem de Contratos do Sistema</h5>
                        <div class="ibox-tools">
                            <button class="btn btn-success " id="btnNovo" onclick="btnNovo()" type="button">  Novo </button>
                        </div>
                    </div>
                    <div class="ibox-content">

                        <div class="table-responsive">
                            <table class="table table-striped table-bordered table-hover dataTables-example">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Codigo</th>
                                        <th>Descrição</th>
                                        <th>Data Início</th>
                                        <th>Data Vigência</th>
                                        <th>Opções</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model.objetoRetorno)
                                    {
                                        <tr class="gradeX">

                                            <td>@item.Id</td>
                                            <td>@item.Codigo</td>
                                            <td>@item.Descricao</td>
                                            <td>@item.DtInicio.ToString("MM/dd/yyyy")</td>
                                            <td>Indeterminado</td>
                                            <td>
                                                <button class="btn btn-info " onclick="btnEdit('@item.Id')" type="button"> Editar</button>
                                                @if (item.IdStatus == 1)
                                                {
                                                    <button class="btn btn-danger " onclick="btnDeletar('@item.Id')" type="button" idcontrato="@item.Id">  Deletar</button>
                                                }                                                                                                         
                                                else                                                                                                      
                                                {                                                                                                         
                                                    <button class="btn btn-success " onclick="btnAtivar('@item.Id')" type="button" idcontrato="@item.Id"> Ativar</button>
                                                }
                                            </td>

                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
}

<script>





    function btnEdit(idContrato) {
        showLoading('Acessando...');
        window.location = '../Contratos/Contrato?idContrato=' + idContrato
    }


    function btnNovo() {
        showLoading('Acessando...');
        window.location = '../Contratos/Contrato'
    }

    function btnAtivar(idContrato) {

        showLoading('Processando...');
        $.ajax({
            url: '../Contratos/Ativar',
            type: 'POST',
            data: { idContrato: idContrato },
            beforeSend: function () {

            },
            onsuccess: function () { },
            success: function (result) {
                if (result.statusRetorno == 'success') {
                    hideLoading();
                    swal("Perfeito", "Item ativado com sucesso!", "success");

                    setTimeout(function () {
                        window.location = "../Contratos";
                    }, 2000);

                }
                else {
                    hideLoading();
                    swal("Atenção", result.statusRetorno, "error");
                }
            }
        });

    }

    function btnDeletar(idContrato) {

        showLoading('Processando...');
        $.ajax({
            url: '../Contratos/Desativar',
            type: 'POST',
            data: { idContrato: idContrato },
            beforeSend: function () {

            },
            onsuccess: function () { },
            success: function (result) {
                if (result.statusRetorno == 'success') {
                    hideLoading();
                    swal("Perfeito", "Item deletado com sucesso!", "success");

                    setTimeout(function () {
                        window.location = "../Contratos";
                    }, 2000);

                }
                else {
                    hideLoading();
                    swal("Atenção", result.statusRetorno, "error");
                }
            }
        });

    }

</script>