backend/Presentation/Controllers/DividendoController.cs
using ApplicationServices.IApplicationServices;
using AutoMapper;
using Domain.Entities._2BTrust;
using Domain.Enuns;
using Newtonsoft.Json;
using Presentation.Helpers;
using Presentation.Models._2BTrustModel;
using RestSharp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Presentation.Controllers
{
    public class DividendoController : BaseController
    {

        public DividendoController()
        {
            

        }
        // GET: Dividendo
        public async Task<ActionResult> Index()
        {
            IEnumerable<PessoaPoolsInvestidosModel> model;
            IRestResponse response = await PostRestAsync<PessoaPoolsInvestidos>("/PoolsBens/GetPessoasPoolsInvestido");
            if (response.StatusCode == System.Net.HttpStatusCode.OK)
            {
                model = JsonConvert.DeserializeObject<IEnumerable<PessoaPoolsInvestidosModel>>(response.Content);

                retorno.statusRetorno = ErrorMessageHttp.GetErrorMessage(response.StatusCode);
                retorno.objetoRetorno = model;

            }
            else
            {
                retorno.statusRetorno = ErrorMessageHttp.GetErrorMessage(response.StatusCode);
                retorno.objetoRetorno = null;

            }

            return View(retorno);
        }


        [HttpPost]
        public async Task<ActionResult> AddDividendo(string dtReferencia, string obs, string dividendo, int idPoolPessoaBem, int cotas, int idPessoa, int IdPoolBem)
        {

            try
            {

                var splitDate = dtReferencia.Split('/');


                DateTime dtLancamento = new DateTime(int.Parse(splitDate[1]), int.Parse(splitDate[0]), 3);
                Lancamentos objDto = new Lancamentos()
                {
                    Credito = true,
                    DtInclusao = DateTime.Now,
                    DtLancamento = dtLancamento,
                    IdPessoa = idPessoa,
                    IdPoolBem = IdPoolBem,
                    IdPoolBemPessoa = idPoolPessoaBem,
                    NumParticao = cotas.ToString(),
                    Obs = obs,
                    Valor = Convert.ToDecimal(dividendo),
                    IdTpLancamento = 1,
                    IdUsuarioInclusao = SessionManager.usuarioLogado.Id

                };

                IRestResponse response = await PutObjectRestAsync<Lancamentos>("/PoolsBens/InsertLancamento", objDto);
                if (response.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    Lancamentos model = JsonConvert.DeserializeObject<Lancamentos>(response.Content);

                    retorno.statusRetorno = ErrorMessageHttp.GetErrorMessage(response.StatusCode);
                    retorno.objetoRetorno = model;

                    if (model == null)
                    {
                        return Json(false, JsonRequestBehavior.AllowGet);

                    }

                    return Json(true, JsonRequestBehavior.AllowGet);

                }
                else
                {
                    retorno.statusRetorno = ErrorMessageHttp.GetErrorMessage(response.StatusCode);
                    retorno.objetoRetorno = null;


                    return Json(false, JsonRequestBehavior.AllowGet);

                }
            }
            catch (Exception ex)
            {

                return Json(false, JsonRequestBehavior.AllowGet);

                throw;
            }

        }


        public async Task<ActionResult> AddDividendo(int id)
        {
            try
            {
                PessoaPoolsInvestidosModel model;
                IRestResponse response = await PostRestAsync<PessoaPoolsInvestidos>("/PoolsBens/GetPessoasPoolsInvestidoById?id=" + id);
                if (response.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    model = JsonConvert.DeserializeObject<PessoaPoolsInvestidosModel>(response.Content);

                    retorno.statusRetorno = ErrorMessageHttp.GetErrorMessage(response.StatusCode);
                    retorno.objetoRetorno = model;

                }
                else
                {
                    retorno.statusRetorno = ErrorMessageHttp.GetErrorMessage(response.StatusCode);
                    retorno.objetoRetorno = null;

                }

                return View(retorno);
            }
            catch (Exception ex)
            {

                throw;
            }
        }
    }
}

backend/Presentation/Views/Dividendo/AddDividendo.cshtml
@model Presentation.Helpers.ResponseJson
@{
    ViewBag.Title = "Index";

    var objModel = (Presentation.Models._2BTrustModel.PessoaPoolsInvestidosModel)Model.objetoRetorno;

}


<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Dividendo para cliente</h2>
        <ol class="breadcrumb">
            <li>
                <a href="../Home">Home</a>
            </li>
            <li>
                <a>Administrativo</a>
            </li>
            <li>
                <a href="../Dividendo">Dividendos</a>
            </li>
            <li class="active">
                <strong>Adicionar Dividendo</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>

@if (Model.statusRetorno != "success")
{
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>Inclusão de dividendos para o cliente</h5>
                        <div class="ibox-tools">

                        </div>
                    </div>
                    <div class="ibox-content">

                        <span> @Model.statusRetorno</span>

                    </div>
                </div>
            </div>
        </div>
    </div>



}
else
{
    <div class="wrapper wrapper-content animated fadeInRight">

        <div id="dvAnexos" class="animated pulse">

            <div class="row wrapper border-bottom white-bg page-heading">
                <div class="col-lg-12">
                    <div class="row">
                        <div class="col-lg-9"><h2>Número da conta: #@objModel.IdPessoa.ToString().PadLeft(6, '0')</h2> </div>
                        <div class="col-lg-3" style=" margin-top: 20px;">
                            <button class="btn btn-danger " style="float:right" type="button" id="btnCancelar" onclick="btnVoltar()">  Voltar </button>
                        </div>
                    </div> 

                    <hr />
                    <div class="row">
                        <div class="col-lg-4">
                            <div class="form-group">
                                <h3>Cliente</h3>
                                <h4 style="color:#9a1b1b">@objModel.NomeCliente</h4>
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="form-group">
                                <h3>Fundo investido</h3>
                                <h4 style="color:#9a1b1b">@objModel.NomePool</h4>
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="form-group">
                                <h3>Cotas</h3>
                                <h4 style="color:#9a1b1b">@objModel.Cotas</h4>
                            </div>
                        </div>
                    </div>
                    <hr />
                    <div class="row">

                        <div class="col-lg-3">
                            <div class="form-group">
                                <label>Data Referência *</label>
                                @Html.TextBox("txtDataReferencia", "", new { @class = "form-control", @placeholder = " " })
                            </div>
                        </div>
                        <div class="col-lg-3">
                            <div class="form-group">
                                <label>Dividendo *</label>
                                @Html.TextBox("txtDividendo", "", new { @class = "form-control money", @placeholder = " " })
                            </div>
                        </div>

                        <div class="col-lg-3">
                            <div class="form-group">
                                <label>Descrição</label>
                                @Html.TextBox("txtObs", "", new { @class = "form-control", @placeholder = " " })
                            </div>
                        </div>

                        <div class="col-lg-3">
                            <div class="form-group" style="padding:22px">
                                <button class="btn btn-info " type="button" onclick="btnIncluir()" autocomplete="off"> Incluir</button>

                            </div>
                        </div>
                    </div>
                    <hr />
                    <div class="row">

                        <div class="col-lg-12"><h2>Histórico</h2></div>

                        <div class="ibox-content">

                            <div class="table-responsive">

                                <div class="row">
                                    <div class="col-lg-12">
                                        <table class="table table-striped table-bordered table-hover dataTables-example">
                                            <thead>
                                                <tr>
                                                    <th>#</th>
                                                    <th>Cotas</th>
                                                    <th>Dividendo</th>
                                                    <th>Descrição</th>
                                                    <th>Mês/Ano Ref.</th>
                                                    <th>Data Incusão</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @foreach (var item in objModel._Lancamentos)
                                {

                                    <tr class="gradeX" style=" ">
                                        <th>@item.Id</th>
                                        <th>@item.NumParticao</th>
                                        <th>@item.Valor.ToString("c")</th>
                                        <th>@item.Obs</th>
                                        <th>@item.DtLancamento.ToString("MM/yyyy")</th>
                                        <th>@item.DtInclusao</th>


                                    </tr>
                }
                                            </tbody>
                                        </table>

                                    </div>
                                </div>


                            </div>

                        </div>
                    </div>



                </div>

            </div>


        </div>
    </div>

}




    <script>

    function btnVoltar() {
        window.location = '../Dividendo'
    }

    function btnIncluir() {

        var dtReferencia = $('#txtDataReferencia').val();
        var obs = $('#txtObs').val();
        var dividendo = $('#txtDividendo').val();
        if (dtReferencia == '' || obs == '' || dividendo == '') {


            swal("Ops!", "Preencha todos os campos.", "error")

        }
        else {

            showLoading('Aplicando dividendos');

            $.ajax({
                /**/
                url: '@Url.Action("AddDividendo", "Dividendo")',
                /**/
                type: 'POST',
                data: { dtReferencia: dtReferencia, obs: obs, dividendo: dividendo, idPoolPessoaBem: @objModel.Id, cotas: @objModel.Cotas, idPessoa:@objModel.IdPessoa, IdPoolBem: @objModel.IdPoolBem},
                success: function (data) {

                    hideLoading();
                    if (data == true) {

                        swal("Feito!", "Dividendo cadastrado com sucesso!", "success");
                        window.location = '../Dividendo'
                    }
                    else {
                        swal("Ops!", "Ocorreu um erro.", "error")
                    }

                }

            });
        }

    }


    window.onload = function (event) {


        $('#txtDataReferencia').attr("data-mask", "99/9999")


    }
    </script>

backend/Presentation/Views/Dividendo/Index.cshtml
@model Presentation.Helpers.ResponseJson
@{
    ViewBag.Title = "Index";


}
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Clientes investindo</h2>
        <ol class="breadcrumb">
            <li>
                <a href="../Home">Home</a>
            </li>
            <li>
                <a>Administrativo</a>
            </li>
            <li class="active">
                <strong>Dividendos</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>


@if (Model.statusRetorno != "success")
{
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>Listagem de Investidores</h5>
                        <div class="ibox-tools">

                        </div>
                    </div>
                    <div class="ibox-content">

                        <span> @Model.statusRetorno</span>

                    </div>
                </div>
            </div>
        </div>
    </div>



}
else
{

    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>Listagem Clientes Investidores</h5>
                        <div class="ibox-tools">
                        </div>
                    </div>
                    <div class="ibox-content">

                        <div class="table-responsive">

                            <div class="row">
                                <div class="col-lg-12">
                                    <table class="table table-striped table-bordered table-hover dataTables-example">
                                        <thead>
                                            <tr>
                                                <th>#</th>
                                                <th>Nome</th>
                                                <th>Investimento</th>
                                                <th>Cotas</th>
                                                <th>Último Dividendo em:</th>
                                                <th>Opções</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach (var item in (IEnumerable<Presentation.Models._2BTrustModel.PessoaPoolsInvestidosModel>)Model.objetoRetorno)
                                            {



                                                var sTyle = "";
                                                if (item.Cotas <50)
                                                { sTyle = ""; }

                                                <tr class="gradeX" style="@sTyle">
                                                    <th>@item.IdPessoa.ToString().PadLeft(6,'0')</th>
                                                    <th>@item.NomeCliente</th>
                                                    <th>@item.NomePool</th>
                                                    <th>@item.Cotas</th>
                                                    <th>@if(item.UltimoLancamento==null)
                                                    { <span> - </span>}
                                                    else
                                                    {  <span> @item.UltimoLancamento.Value.ToString("MM/yyyy") </span>}

                                                    </th>
                                                    <th>
                                                        <button class="btn btn-info " type="button" onclick="btnEdit('@item.Id')" autocomplete="off">  Info</button>
                                                    </th>

                                                </tr>
                                            }
                                        </tbody>
                                    </table>

                                </div>
                            </div>


                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
}

<script>
    function btnEdit(id) {
        showLoading('Acessando...');
        window.location = '../Dividendo/AddDividendo?id=' + id
    }
    function btnAtivar(idCliente) {

        showLoading('Processando...');
        $.ajax({
            url: '../Clientes/Ativar',
            type: 'POST',
            data: { idCliente: idCliente },
            beforeSend: function () {

            },
            onsuccess: function () { },
            success: function (result) {
                if (result.statusRetorno == 'success') {
                    hideLoading();
                    swal("Perfeito", "Item ativado com sucesso!", "success");

                    setTimeout(function () {
                        window.location = "../Clientes";
                    }, 2000);

                }
                else {
                    hideLoading();
                    swal("Atenção", result.statusRetorno, "error");
                }
            }
        });

    }

    function btnDeletar(idCliente) {

        showLoading('Processando...');
        $.ajax({
            url: '../Clientes/Desativar',
            type: 'POST',
            data: { idCliente: idCliente },
            beforeSend: function () {

            },
            onsuccess: function () { },
            success: function (result) {
                if (result.statusRetorno == 'success') {
                    hideLoading();
                    swal("Perfeito", "Item deletado com sucesso!", "success");

                    setTimeout(function () {
                        window.location = "../Clientes";
                    }, 2000);

                }
                else {
                    hideLoading();
                    swal("Atenção", result.statusRetorno, "error");
                }
            }
        });

    }
</script>